const http=require("node:http"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const {DatabaseSync}=require("node:sqlite");
const root=__dirname,port=Number(process.env.PORT||8765),db=new DatabaseSync(process.env.LINCY_DB||path.join(root,"lincy.sqlite")),sessions=new Map();
const emptyPlan=()=>({meals:{},settings:{region:"Sweden",units:"metric"},checked:{},shoppingOverrides:{},recipeChecks:{}});
db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS households(id INTEGER PRIMARY KEY,name TEXT NOT NULL,invite_code TEXT UNIQUE NOT NULL,plan TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,household_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,FOREIGN KEY(household_id) REFERENCES households(id));`);
function json(res,status,data,cookie){res.writeHead(status,{"Content-Type":"application/json",...(cookie?{"Set-Cookie":cookie}:{})});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let raw="";req.on("data",c=>{raw+=c;if(raw.length>2e6)reject(new Error("Request too large"));});req.on("end",()=>{try{resolve(JSON.parse(raw||"{}"));}catch{reject(new Error("Invalid JSON"));}});});}
function hash(password,salt){return crypto.scryptSync(password,salt,64).toString("hex");}
function sessionUser(req){const token=(req.headers.cookie||"").match(/(?:^|; )lincy_session=([^;]+)/)?.[1],id=token&&sessions.get(token);return id?db.prepare("SELECT users.id,users.name,users.email,users.household_id,households.name household_name,households.invite_code FROM users JOIN households ON households.id=users.household_id WHERE users.id=?").get(id):null;}
function openSession(res,user){const token=crypto.randomBytes(32).toString("hex");sessions.set(token,user.id);json(res,200,{ok:true},`lincy_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`);}
async function api(req,res,url){
 if(req.method==="POST"&&url.pathname==="/api/register"){const d=await body(req),email=String(d.email||"").trim().toLowerCase();if(!d.name||!email||String(d.password||"").length<8)return json(res,400,{error:"Name, email and an 8-character password are required."});if(db.prepare("SELECT id FROM users WHERE email=?").get(email))return json(res,409,{error:"That email already has an account."});let home;if(d.inviteCode)home=db.prepare("SELECT * FROM households WHERE invite_code=?").get(String(d.inviteCode).trim().toUpperCase());else if(d.householdName){const code=crypto.randomBytes(4).toString("hex").toUpperCase();db.prepare("INSERT INTO households(name,invite_code,plan,updated_at) VALUES(?,?,?,?)").run(String(d.householdName).trim(),code,JSON.stringify(emptyPlan()),new Date().toISOString());home=db.prepare("SELECT * FROM households WHERE invite_code=?").get(code);}if(!home)return json(res,400,{error:"Enter a kitchen name or a valid invite code."});const salt=crypto.randomBytes(16).toString("hex");const result=db.prepare("INSERT INTO users(household_id,name,email,password_hash,salt) VALUES(?,?,?,?,?)").run(home.id,String(d.name).trim(),email,hash(d.password,salt),salt);openSession(res,{id:Number(result.lastInsertRowid)});return;}
 if(req.method==="POST"&&url.pathname==="/api/login"){const d=await body(req),user=db.prepare("SELECT * FROM users WHERE email=?").get(String(d.email||"").trim().toLowerCase());if(!user||hash(String(d.password||""),user.salt)!==user.password_hash)return json(res,401,{error:"Email or password is incorrect."});openSession(res,user);return;}
 if(req.method==="POST"&&url.pathname==="/api/logout"){const token=(req.headers.cookie||"").match(/(?:^|; )lincy_session=([^;]+)/)?.[1];if(token)sessions.delete(token);return json(res,200,{ok:true},"lincy_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0");}
 const user=sessionUser(req);if(!user)return json(res,401,{error:"Please log in."});
 if(req.method==="GET"&&url.pathname==="/api/plan"){const row=db.prepare("SELECT plan,updated_at FROM households WHERE id=?").get(user.household_id);return json(res,200,{user:{name:user.name,email:user.email},household:{name:user.household_name,inviteCode:user.invite_code},state:JSON.parse(row.plan),updatedAt:row.updated_at});}
 if(req.method==="PUT"&&url.pathname==="/api/plan"){const d=await body(req);if(!d.state||typeof d.state!=="object")return json(res,400,{error:"Invalid plan."});const updatedAt=new Date().toISOString();db.prepare("UPDATE households SET plan=?,updated_at=? WHERE id=?").run(JSON.stringify(d.state),updatedAt,user.household_id);return json(res,200,{ok:true,updatedAt});}json(res,404,{error:"Not found"});
}
const types={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json",".webmanifest":"application/manifest+json"};
http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith("/api/"))return await api(req,res,url);const relative=url.pathname==="/"?"index.html":decodeURIComponent(url.pathname.slice(1)),file=path.resolve(root,relative);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end("Not found");}res.writeHead(200,{"Content-Type":types[path.extname(file)]||"application/octet-stream","Cache-Control":"no-cache"});fs.createReadStream(file).pipe(res);}catch(error){console.error(error);json(res,500,{error:"Something went wrong."});}}).listen(port,()=>console.log(`Lincy is running at http://localhost:${port}`));
